#!/bin/sh
case $1 in
"help"|"--help"|"-h")
	echo "Usage: ./dock <command>

	commands:
		build	- build the docker image
		run 	- run the container
		deploy	- push the image
		remove	- remove the image"
	;;
"build")
	docker build -t syrus/mongo .
	;;
"run")
	docker container run -it syrus/mongo /bin/sh
	;;
"deploy")
	docker push syrus/mongo
	;;
"remove")
	docker rmi -f syrus/mongo
	;;
esac
